import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/src/providers/QueryProvider";
import SideBar from "@/src/components/Sidebar/SideBar";
import Navbar from "@/src/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="flex dark:bg-gray-800">
            <SideBar />
            <div className="ml-[230px] mt-10 w-[75%]">
              <Navbar />
              <Toaster position="top-right" reverseOrder={false} />
              <main>{children}</main>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
